# Generated by Django 5.1.1 on 2024-10-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vayal_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vayal_user',
            old_name='genter',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='vayal_user',
            name='aadhar_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='vayal_user',
            name='cast',
            field=models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('OEC', 'OEC')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vayal_user',
            name='district',
            field=models.CharField(default='Kozhikode', max_length=225),
        ),
        migrations.AddField(
            model_name='vayal_user',
            name='house_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='vayal_user',
            name='land_ownership',
            field=models.CharField(choices=[('Own', 'Own'), ('Lease', 'Lease')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vayal_user',
            name='muncipality',
            field=models.CharField(default='Kozhikode', max_length=225),
        ),
        migrations.AddField(
            model_name='vayal_user',
            name='photo',
            field=models.ImageField(null=True, upload_to='documents/photo/'),
        ),
        migrations.AddField(
            model_name='vayal_user',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='vayal_user',
            name='place',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='vayal_user',
            name='village',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
