# Generated by Django 5.1.2 on 2024-10-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vayal_user', '0002_remove_vayal_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vayal_user',
            name='photo',
            field=models.ImageField(default=1, upload_to='photo'),
            preserve_default=False,
        ),
    ]
