# Generated by Django 5.1.2 on 2024-10-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vayal_user', '0003_vayal_user_vegetable_permission_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vayal_user',
            name='vegetable_permission',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=225),
        ),
        migrations.AlterField(
            model_name='vayal_user',
            name='vegetable_permission_applied',
            field=models.CharField(default='False', max_length=225),
        ),
    ]
