# Generated by Django 5.1.2 on 2024-10-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vayal_user', '0003_alter_vayal_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vayal_user',
            name='photo',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
