# Generated by Django 5.1.2 on 2024-10-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vayal_user', '0004_alter_vayal_user_vegetable_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vayal_user',
            name='cast',
            field=models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC/ST', 'SC/ST')], max_length=20),
        ),
    ]
