# Generated by Django 5.1.1 on 2024-10-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vayal_user', '0004_alter_vayal_user_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vayal_user',
            name='land_ownership',
            field=models.CharField(choices=[('Own', 'Own'), ('Lease', 'Lease')], max_length=20),
        ),
    ]
