# Generated by Django 5.1.2 on 2024-10-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vayal_user', '0006_alter_vayal_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vayal_user',
            name='vegetable_permission',
            field=models.CharField(default='Pending', max_length=225),
        ),
    ]
