# Generated by Django 5.1.2 on 2024-10-22 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vayal_user', '0007_vayal_user_vegetable_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('period', models.IntegerField()),
                ('land_lease_rent', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='land')),
                ('vayal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vayal_user.vayal_user')),
            ],
        ),
    ]
