# Generated by Django 5.1.1 on 2024-10-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vayal_user', '0007_alter_vayal_user_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vayal_user',
            name='aadhar_number',
            field=models.CharField(max_length=12),
        ),
    ]
