# Generated by Django 5.1.1 on 2024-10-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vayal_user', '0008_alter_vayal_user_aadhar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vayal_user',
            name='cast',
            field=models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('OEC', 'OEC')], max_length=20),
        ),
    ]
