# Generated by Django 5.1.1 on 2024-09-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VegitableForm',
            new_name='VegitablePermissionForm',
        ),
    ]
