# Generated by Django 5.1.1 on 2024-09-17 14:55

import officer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0002_schemapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemapplication',
            name='benefinting',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='schemapplication',
            name='photo',
            field=models.ImageField(upload_to='documents/photo/', validators=[officer.models.validate_image]),
        ),
    ]
