# Generated by Django 5.1.1 on 2024-09-27 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0002_rename_vegitableform_vegitablepermissionform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hm_user',
            name='account',
        ),
    ]
