# Generated by Django 5.1.1 on 2024-09-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='HM_User',
        ),
    ]
