# Generated by Django 5.1.1 on 2024-09-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('Janakeeyasoothranam', 'Janakeeyasoothranam'), ('Department of agriculture', 'Department of agriculture')], max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('criteria', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField()),
            ],
        ),
    ]
