# Generated by Django 5.1.2 on 2024-10-27 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vayal_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('Janakeeyasoothranam', 'Janakeeyasoothranam'), ('Department of agriculture', 'Department of agriculture')], max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('criteria', models.CharField(max_length=250)),
                ('cast_eligibility', models.CharField(choices=[('All', 'All'), ('General', 'General'), ('OBC', 'OBC'), ('SC/ST', 'SC/ST')], default='All', max_length=50)),
                ('land_ownership', models.CharField(choices=[('Own', 'Own'), ('Lease', 'Lease')], default='All', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Unresolvable', 'Unresolvable')], default='Pending', max_length=50)),
                ('vayal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vayal_user.vayal_user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vayal_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vayal_user.vayal_user')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefiting', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('house_number', models.CharField(max_length=250)),
                ('ward_number', models.CharField(max_length=250)),
                ('total_land_area', models.CharField(max_length=255)),
                ('land_survay_no', models.CharField(max_length=5)),
                ('bank_name', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=19)),
                ('sign', models.ImageField(upload_to='sign/')),
                ('aadhar', models.ImageField(upload_to='aadhar/')),
                ('land_tax', models.ImageField(upload_to='land_tax/')),
                ('bank_pass', models.ImageField(upload_to='bank_pass/')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.scheme')),
                ('vayal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vayal_user.vayal_user')),
            ],
        ),
        migrations.CreateModel(
            name='VegetablePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=250)),
                ('farm_place', models.CharField(max_length=250)),
                ('total_land_area', models.CharField(max_length=255)),
                ('land_survay_no', models.CharField(max_length=5)),
                ('sign', models.ImageField(upload_to='vegetable_permission/sign/')),
                ('aadhar', models.FileField(upload_to='vegetable_permission/aadhar/')),
                ('land_tax', models.FileField(upload_to='vegetable_permission/land_tax/')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('vayal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vayal_user.vayal_user')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('expiry', models.IntegerField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='vegetables')),
                ('farm_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.vegetablepermission')),
            ],
        ),
        migrations.CreateModel(
            name='VegetablePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('vayal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vayal_user.vayal_user')),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.vegetable')),
            ],
        ),
    ]
