# Generated by Django 5.1.2 on 2024-10-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable',
            name='vayal_user',
        ),
    ]
