# Generated by Django 5.1.2 on 2024-10-19 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0001_initial'),
        ('vayal_user', '0005_remove_vayal_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='vayal_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vayal_user.vayal_user'),
        ),
    ]
