# Generated by Django 5.1.1 on 2024-10-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vayal_User',
        ),
    ]
