# Generated by Django 5.1.2 on 2024-10-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0002_remove_vegetable_vayal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetablepermission',
            name='land_survay_no',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegetablepermission',
            name='total_land_area',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
