# Generated by Django 5.1.1 on 2024-10-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0002_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schem',
            new_name='Scheme',
        ),
    ]
