# Generated by Django 5.1.2 on 2024-10-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0002_remove_schemeapplication_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseland',
            name='photo',
            field=models.ImageField(upload_to='land'),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='photo',
            field=models.ImageField(upload_to='vegetables'),
        ),
    ]
