# Generated by Django 5.1.2 on 2024-10-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0003_vegetablepermission_land_survay_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetablepermission',
            name='aadhar',
            field=models.ImageField(default=1, upload_to='vegetable_permission/aadhar/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegetablepermission',
            name='land_tax',
            field=models.ImageField(default=1, upload_to='vegetable_permission/land_tax/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vegetablepermission',
            name='sign',
            field=models.ImageField(default=1, upload_to='vegetable_permission/sign/'),
            preserve_default=False,
        ),
    ]
