# Generated by Django 5.1.2 on 2024-10-27 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0003_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefiting', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('house_number', models.CharField(max_length=250)),
                ('ward_number', models.CharField(max_length=250)),
                ('total_land_area', models.CharField(max_length=255)),
                ('land_survay_no', models.CharField(max_length=5)),
                ('bank_name', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=19)),
                ('sign', models.ImageField(upload_to='scheme/sign/')),
                ('aadhar', models.FileField(upload_to='scheme/aadhar/')),
                ('land_tax', models.FileField(upload_to='scheme/land_tax/')),
                ('bank_pass', models.FileField(upload_to='scheme/bank_pass/')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.agricultural_officer')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.scheme')),
                ('vayal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.vayal_user')),
            ],
        ),
    ]
