# Generated by Django 5.1.2 on 2024-10-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0003_alter_leaseland_photo_alter_vegetable_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeapplication',
            name='aadhar',
            field=models.ImageField(upload_to='aadhar'),
        ),
        migrations.AlterField(
            model_name='schemeapplication',
            name='bank_pass',
            field=models.ImageField(upload_to='bank_pass'),
        ),
        migrations.AlterField(
            model_name='schemeapplication',
            name='land_tax',
            field=models.ImageField(upload_to='land_tax'),
        ),
        migrations.AlterField(
            model_name='schemeapplication',
            name='sign',
            field=models.ImageField(upload_to='sign'),
        ),
    ]
