# Generated by Django 5.1.2 on 2024-10-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0004_scheme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scheme',
        ),
    ]
