# Generated by Django 5.1.1 on 2024-10-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0005_vegetablepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetablepermission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
