# Generated by Django 5.1.2 on 2024-10-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0005_alter_schemeapplication_aadhar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaseLand',
        ),
    ]
