# Generated by Django 5.1.2 on 2024-10-27 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0005_vegetablepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('expiry', models.IntegerField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='vegetables')),
                ('farm_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.vegetablepermission')),
            ],
        ),
    ]
