# Generated by Django 5.1.2 on 2024-10-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0006_alter_vegetablepermission_land_tax_vegetablepurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='published',
        ),
        migrations.RemoveField(
            model_name='vegetablepurchase',
            name='id',
        ),
        migrations.AddField(
            model_name='vegetablepurchase',
            name='purchase_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
