# Generated by Django 5.1.2 on 2024-10-27 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0006_vegetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetablePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('vayal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.vayal_user')),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.vegetable')),
            ],
        ),
    ]
