# Generated by Django 5.1.2 on 2024-10-27 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0007_vegetablepurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Unresolvable', 'Unresolvable')], default='Pending', max_length=50)),
                ('vayal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.vayal_user')),
            ],
        ),
    ]
