# Generated by Django 5.1.2 on 2024-10-21 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0007_schemeapplication'),
        ('vayal_user', '0005_remove_vayal_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemeapplication',
            name='aadhar',
            field=models.ImageField(upload_to='documents/aadhar'),
        ),
        migrations.AlterField(
            model_name='schemeapplication',
            name='bank_pass',
            field=models.ImageField(upload_to='documents/bank_pass'),
        ),
        migrations.AlterField(
            model_name='schemeapplication',
            name='land_tax',
            field=models.ImageField(upload_to='documents/land_tax'),
        ),
        migrations.AlterField(
            model_name='schemeapplication',
            name='photo',
            field=models.ImageField(upload_to='documents/photo'),
        ),
        migrations.AlterField(
            model_name='schemeapplication',
            name='sign',
            field=models.ImageField(upload_to='documents/sign'),
        ),
        migrations.CreateModel(
            name='VegetablePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=150)),
                ('farm_place', models.TextField()),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('vayal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vayal_user.vayal_user')),
            ],
        ),
    ]
