# Generated by Django 5.1.2 on 2024-10-27 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0008_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vayal_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='officer.vayal_user')),
            ],
        ),
    ]
