# Generated by Django 5.1.2 on 2024-10-21 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0008_alter_schemeapplication_aadhar_and_more'),
        ('vayal_user', '0005_remove_vayal_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetablepermission',
            name='farm_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vegetablepermission',
            name='farm_place',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('quantity', models.CharField(max_length=250)),
                ('expiry', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='photo')),
                ('farm_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.vegetablepermission')),
                ('vayal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vayal_user.vayal_user')),
            ],
        ),
    ]
