# Generated by Django 5.1.2 on 2024-10-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0008_scheme_caste_eligibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='caste_eligibility',
            new_name='cast_eligibility',
        ),
    ]
