# Generated by Django 5.1.2 on 2024-10-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0009_rename_caste_eligibility_scheme_cast_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='land_ownership',
            field=models.CharField(choices=[('Own', 'Own'), ('Lease', 'Lease')], default='All', max_length=20),
        ),
    ]
