# Generated by Django 5.1.2 on 2024-10-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0009_alter_vegetablepermission_farm_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
