# Generated by Django 5.1.2 on 2024-10-27 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('period', models.IntegerField()),
                ('land_lease_rent', models.IntegerField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='photo/')),
                ('vayal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.vayal_user')),
            ],
        ),
    ]
