# Generated by Django 5.1.2 on 2024-10-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0010_scheme_land_ownership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetablepurchase',
            name='purchase_id',
        ),
        migrations.RemoveField(
            model_name='vegetablepurchase',
            name='token_number',
        ),
        migrations.AddField(
            model_name='vegetablepurchase',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
