# Generated by Django 5.1.2 on 2024-10-27 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0011_alter_schemeapplication_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='officer.agricultural_officer'),
        ),
    ]
