# Generated by Django 5.1.2 on 2024-10-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0012_complaint_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='cast_eligibility',
            field=models.CharField(choices=[('All', 'All'), ('General', 'General'), ('OBC', 'OBC'), ('SC/ST', 'SC/ST')], default='All', max_length=50),
        ),
    ]
