# Generated by Django 5.1.1 on 2024-10-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vayal_user', '0002_rename_genter_vayal_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vayal_user',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
