# Generated by Django 5.1.1 on 2024-10-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vayal_user', '0006_alter_vayal_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vayal_user',
            name='place',
            field=models.CharField(max_length=225),
        ),
    ]
